export interface MonthlyRevenueData {
  month: string;
  projetado: number;
  realizado: number;
}

export const data2025: MonthlyRevenueData[] = [
  { month: 'Jan', projetado: 320000, realizado: 310000 },
  { month: 'Fev', projetado: 350000, realizado: 365000 },
  { month: 'Mar', projetado: 380000, realizado: 390000 },
  { month: 'Abr', projetado: 410000, realizado: 405000 },
  { month: 'Mai', projetado: 440000, realizado: 460000 },
  { month: 'Jun', projetado: 480000, realizado: 510000 },
  { month: 'Jul', projetado: 510000, realizado: 520000 },
  { month: 'Ago', projetado: 550000, realizado: 540000 },
  { month: 'Set', projetado: 580000, realizado: 610000 },
  { month: 'Out', projetado: 620000, realizado: 635000 },
  { month: 'Nov', projetado: 660000, realizado: 680000 },
  { month: 'Dez', projetado: 700000, realizado: 730000 },
];

export const data2026: MonthlyRevenueData[] = [
  { month: 'Jan', projetado: 750000, realizado: 780000 },
  { month: 'Fev', projetado: 800000, realizado: 820000 },
  { month: 'Mar', projetado: 850000, realizado: 890000 },
  { month: 'Abr', projetado: 900000, realizado: 915000 },
  { month: 'Mai', projetado: 950000, realizado: 980000 },
  { month: 'Jun', projetado: 1000000, realizado: 1050000 },
  { month: 'Jul', projetado: 1050000, realizado: 1080000 },
  { month: 'Ago', projetado: 1100000, realizado: 1120000 },
  { month: 'Set', projetado: 1150000, realizado: 0 },
  { month: 'Out', projetado: 1200000, realizado: 0 },
  { month: 'Nov', projetado: 1250000, realizado: 0 },
  { month: 'Dez', projetado: 1300000, realizado: 0 },
];

export const SERVICES: any[] = [
  {
    id: "domesticos",
    cat: "Serviços Domésticos",
    g: "dom",
    name: "Serviços Domésticos",
    description: "Empregadas domésticas, babás, cozinheiros, passadeiras, cuidadores e gestão integrada do lar.",
    icon: "🧹",
    items: [
      {
        id: "dom1",
        name: "Empregada doméstica (diarista ou mensal)",
        n: "Empregada doméstica (diarista ou mensal)",
        d: "Serviço doméstico completo para manutenção, arrumação diária ou contratação fixa mensal.",
        category: "dom",
        price: 1500,
        priceMzn: 1500,
        unit: "diária / intervenção",
        active: true,
        hasProviders: true,
        providerCount: 28,
        emg: false
      },
      {
        id: "dom2",
        name: "Cozinheiro(a) doméstico(a)",
        n: "Cozinheiro(a) doméstico(a)",
        d: "Confeção de refeições saudáveis, culinária moçambicana e internacional para o dia a dia familiar.",
        category: "dom",
        price: 2500,
        priceMzn: 2500,
        unit: "dia / serviço",
        active: true,
        hasProviders: true,
        providerCount: 14,
        emg: false
      },
      {
        id: "dom3",
        name: "Passadeira / engomadoria ao domicílio",
        n: "Passadeira / engomadoria ao domicílio",
        d: "Tratamento cuidado e engomadoria profissional de roupas no seu domicílio com pontualidade.",
        category: "dom",
        price: 1800,
        priceMzn: 1800,
        unit: "sessão",
        active: true,
        hasProviders: true,
        providerCount: 16,
        emg: false
      },
      {
        id: "dom4",
        name: "Lavandaria ao domicílio",
        n: "Lavandaria ao domicílio",
        d: "Lavagem, tratamento de nódoas e higienização de roupas, têxteis e lençóis na residência.",
        category: "dom",
        price: 2000,
        priceMzn: 2000,
        unit: "sessão / carga",
        active: true,
        hasProviders: true,
        providerCount: 12,
        emg: false
      },
      {
        id: "dom5",
        name: "Motorista particular",
        n: "Motorista particular",
        d: "Condução defensiva e segura, transporte familiar, apoio escolar e gestão de deslocações.",
        category: "dom",
        price: 2200,
        priceMzn: 2200,
        unit: "dia / diária",
        active: true,
        hasProviders: true,
        providerCount: 10,
        emg: false
      },
      {
        id: "dom6",
        name: "Segurança doméstica / guarda-costas residencial",
        n: "Segurança doméstica / guarda-costas residencial",
        d: "Vigilância privada, controlo de acessos residenciais e proteção física da família e propriedade.",
        category: "dom",
        price: 2500,
        priceMzn: 2500,
        unit: "turno / dia",
        active: true,
        hasProviders: true,
        providerCount: 9,
        emg: true
      },
      {
        id: "dom7",
        name: "Cuidador(a) de idosos",
        n: "Cuidador(a) de idosos",
        d: "Apoio humanizado, auxílio na mobilidade, administração de medicação e companhia a seniores.",
        category: "dom",
        price: 2500,
        priceMzn: 2500,
        unit: "dia / turno",
        active: true,
        hasProviders: true,
        providerCount: 11,
        emg: true
      },
      {
        id: "dom8",
        name: "Babá / ama para crianças",
        n: "Babá / ama para crianças",
        d: "Cuidados atenciosos, alimentação infantil, acompanhamento escolar e rotinas lúdicas seguras.",
        category: "dom",
        price: 1800,
        priceMzn: 1800,
        unit: "dia / turno",
        active: true,
        hasProviders: true,
        providerCount: 19,
        emg: true
      },
      {
        id: "dom9",
        name: "Ama especializada em recém-nascidos",
        n: "Ama especializada em recém-nascidos",
        d: "Apoio no pós-parto, cuidados neonatais, amamentação, rotinas de sono e higiene do bebé.",
        category: "dom",
        price: 2500,
        priceMzn: 2500,
        unit: "dia / noite",
        active: true,
        hasProviders: true,
        providerCount: 8,
        emg: true
      },
      {
        id: "dom10",
        name: "Explicador / apoio escolar (ATL)",
        n: "Explicador / apoio escolar (ATL)",
        d: "Acompanhamento pedagógico ao domicílio, reforço em matemática, ciências, línguas e preparação para exames.",
        category: "dom",
        price: 1500,
        priceMzn: 1500,
        unit: "sessão / hora",
        active: true,
        hasProviders: true,
        providerCount: 15,
        emg: false
      },
      {
        id: "dom11",
        name: "Cuidador(a) de pessoas com necessidades especiais",
        n: "Cuidador(a) de pessoas com necessidades especiais",
        d: "Apoio especializado e dedicado a pessoas com limitações motoras, cognitivas ou crónicas.",
        category: "dom",
        price: 2800,
        priceMzn: 2800,
        unit: "dia / turno",
        active: true,
        hasProviders: true,
        providerCount: 7,
        emg: true
      },
      {
        id: "dom12",
        name: "Governanta doméstica",
        n: "Governanta doméstica",
        d: "Gestão executiva do lar, supervisão de equipa doméstica, compras, inventário e coordenação de residência.",
        category: "dom",
        price: 3500,
        priceMzn: 3500,
        unit: "dia / intervenção",
        active: true,
        hasProviders: true,
        providerCount: 6,
        emg: false
      }
    ]
  },
  {
    id: "limpeza",
    cat: "Limpeza Especializada",
    g: "limp",
    name: "Limpeza Especializada",
    description: "Limpeza pós-obra, escritórios, estofos, fossas sépticas, vidros, desinfestação e caixas de água.",
    icon: "✨",
    items: [
      {
        id: "limp1",
        name: "Limpeza pós-obra",
        n: "Limpeza pós-obra",
        d: "Remoção de restos de tinta, cimento, gesso, poeiras finas e higienização terminal pós-construção.",
        category: "limp",
        price: 7500,
        priceMzn: 7500,
        unit: "serviço / dia",
        active: true,
        hasProviders: true,
        providerCount: 16,
        emg: false
      },
      {
        id: "limp2",
        name: "Limpeza de escritórios e espaços comerciais",
        n: "Limpeza de escritórios e espaços comerciais",
        d: "Higienização corporativa periódica de postos de trabalho, copas, sanitários e salas de reunião.",
        category: "limp",
        price: 5500,
        priceMzn: 5500,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 14,
        emg: false
      },
      {
        id: "limp3",
        name: "Limpeza de estofos, sofás e tapetes",
        n: "Limpeza de estofos, sofás e tapetes",
        d: "Extração profunda a vapor de ácaros, manchas e odores em sofás, colchões, carpetes e cadeiras.",
        category: "limp",
        price: 2800,
        priceMzn: 2800,
        unit: "unidade / sessão",
        active: true,
        hasProviders: true,
        providerCount: 12,
        emg: false
      },
      {
        id: "limp4",
        name: "Limpeza de fossas sépticas e tanques",
        n: "Limpeza de fossas sépticas e tanques",
        d: "Despejo, sucção mecânica e desassoreamento de fossas sépticas, caixas de gordura e sumidouros.",
        category: "limp",
        price: 6500,
        priceMzn: 6500,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 8,
        emg: true
      },
      {
        id: "limp5",
        name: "Limpeza de vidros e fachadas",
        n: "Limpeza de vidros e fachadas",
        d: "Lavagem especializada de caixilharias, montras comerciais, clarabóias e vidraças em altura com segurança.",
        category: "limp",
        price: 4500,
        priceMzn: 4500,
        unit: "serviço",
        active: true,
        hasProviders: true,
        providerCount: 7,
        emg: false
      },
      {
        id: "limp6",
        name: "Desinfestação (baratas, ratos, térmitas)",
        n: "Desinfestação (baratas, ratos, térmitas)",
        d: "Fumigação e controlo de pragas urbanas certificada contra baratas, roedores, térmitas e formigas.",
        category: "limp",
        price: 3800,
        priceMzn: 3800,
        unit: "aplicação",
        active: true,
        hasProviders: true,
        providerCount: 10,
        emg: true
      },
      {
        id: "limp7",
        name: "Limpeza e desinfeção de caixas de água",
        n: "Limpeza e desinfeção de caixas de água",
        d: "Esvaziamento, escovagem técnica, cloração e desinfeção de reservatórios de água potável e tanques.",
        category: "limp",
        price: 3200,
        priceMzn: 3200,
        unit: "caixa / tanque",
        active: true,
        hasProviders: true,
        providerCount: 9,
        emg: false
      }
    ]
  },
  {
    id: "manutencao",
    cat: "Manutenção & Reparações",
    g: "man",
    name: "Manutenção & Reparações",
    description: "Eletricistas, canalizadores, ar condicionado, eletrodomésticos, geradores, caixilharia e portões automáticos.",
    icon: "🔧",
    items: [
      {
        id: "man1",
        name: "Eletricista residencial e industrial",
        n: "Eletricista residencial e industrial",
        d: "Diagnóstico de curto-circuito, quadros elétricos, disjuntores, fiação, iluminação e tomadas trifásicas.",
        category: "man",
        price: 2500,
        priceMzn: 2500,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 22,
        emg: true
      },
      {
        id: "man2",
        name: "Canalizador / picheleiro",
        n: "Canalizador / picheleiro",
        d: "Reparação de fugas de água, desentupimentos de esgotos, tubagens PPR/PVC, autoclismos e torneiras.",
        category: "man",
        price: 2200,
        priceMzn: 2200,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 20,
        emg: true
      },
      {
        id: "man3",
        name: "Técnico de climatização (ar condicionado)",
        n: "Técnico de climatização (ar condicionado)",
        d: "Instalação de splits, recarga de gás refrigerante, higienização de filtros e diagnóstico de placas de AC.",
        category: "man",
        price: 3000,
        priceMzn: 3000,
        unit: "unidade / revisão",
        active: true,
        hasProviders: true,
        providerCount: 17,
        emg: true
      },
      {
        id: "man4",
        name: "Técnico de eletrodomésticos",
        n: "Técnico de eletrodomésticos",
        d: "Reparo ao domicílio de máquinas de lavar roupa, loiça, frigoríficos, congeladores e fornos elétricos.",
        category: "man",
        price: 2000,
        priceMzn: 2000,
        unit: "diagnóstico / reparo",
        active: true,
        hasProviders: true,
        providerCount: 13,
        emg: false
      },
      {
        id: "man5",
        name: "Técnico de geradores",
        n: "Técnico de geradores",
        d: "Manutenção preventiva e corretiva de geradores a diesel e gasolina, filtros, baterias e quadros ATS.",
        category: "man",
        price: 4500,
        priceMzn: 4500,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 9,
        emg: true
      },
      {
        id: "man6",
        name: "Montador de Caixilharia de Alumínio (portas e janelas)",
        n: "Montador de Caixilharia de Alumínio (portas e janelas)",
        d: "Instalação, afinação e substituição de portas de alumínio, janelas de correr, fechos e borrachas de vedação.",
        category: "man",
        price: 3500,
        priceMzn: 3500,
        unit: "vão / instalação",
        active: true,
        hasProviders: true,
        providerCount: 11,
        emg: false
      },
      {
        id: "man7",
        name: "Serralheiro",
        n: "Serralheiro",
        d: "Reparação e soldadura de grades de segurança, portões manuais, fechaduras blindadas e estruturas metálicas.",
        category: "man",
        price: 2800,
        priceMzn: 2800,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 12,
        emg: true
      },
      {
        id: "man8",
        name: "Técnico de portões automáticos e motorização",
        n: "Técnico de portões automáticos e motorização",
        d: "Instalação de motores Centurion/ET, programação de comandos, cremalheiras e fotocélulas de segurança.",
        category: "man",
        price: 4000,
        priceMzn: 4000,
        unit: "intervenção / motor",
        active: true,
        hasProviders: true,
        providerCount: 8,
        emg: true
      }
    ]
  },
  {
    id: "carpintaria",
    cat: "Carpintaria & Marcenaria",
    g: "carp",
    name: "Carpintaria & Marcenaria",
    description: "Mobiliário sob medida, acabamentos de portas e roupeiros, restauro, pisos em madeira e coberturas.",
    icon: "🪚",
    items: [
      {
        id: "carp1",
        name: "Carpinteiro de mobiliário sob medida",
        n: "Carpinteiro de mobiliário sob medida",
        d: "Fabrico personalizado de cozinhas planejadas, estantes, closets, secretárias e balcões de atendimento.",
        category: "carp",
        price: 4000,
        priceMzn: 4000,
        unit: "peça / projeto",
        active: true,
        hasProviders: true,
        providerCount: 14,
        emg: false
      },
      {
        id: "carp2",
        name: "Marceneiro de acabamentos (portas, roupeiros, cozinhas)",
        n: "Marceneiro de acabamentos (portas, roupeiros, cozinhas)",
        d: "Ajuste e instalação de portas interiores, aros, dobradiças com amortecedor, corrediças e puxadores.",
        category: "carp",
        price: 3500,
        priceMzn: 3500,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 12,
        emg: false
      },
      {
        id: "carp3",
        name: "Restauro de móveis antigos",
        n: "Restauro de móveis antigos",
        d: "Recuperação estrutural, lixamento, envernizamento à boneca e tratamento anti-térmita de móveis de valor.",
        category: "carp",
        price: 3200,
        priceMzn: 3200,
        unit: "peça",
        active: true,
        hasProviders: true,
        providerCount: 7,
        emg: false
      },
      {
        id: "carp4",
        name: "Instalação de pavimentos em madeira/laminado",
        n: "Instalação de pavimentos em madeira/laminado",
        d: "Colocação de piso flutuante, soalhos de madeira, rodapés e nivelamento de base com isolamento térmico.",
        category: "carp",
        price: 850,
        priceMzn: 850,
        unit: "m²",
        active: true,
        hasProviders: true,
        providerCount: 8,
        emg: false
      },
      {
        id: "carp5",
        name: "Construção de estruturas em madeira (telhados, pérgolas, decks)",
        n: "Construção de estruturas em madeira (telhados, pérgolas, decks)",
        d: "Montagem de asnas de telhado, pérgolas de jardim, sombreamentos e decks de madeira tratada com proteção UV.",
        category: "carp",
        price: 9500,
        priceMzn: 9500,
        unit: "estrutura",
        active: true,
        hasProviders: true,
        providerCount: 6,
        emg: false
      }
    ]
  },
  {
    id: "construcao",
    cat: "Construção & Obras",
    g: "obra",
    name: "Construção & Obras",
    description: "Pedreiros, pintores, ladrilhadores, gesseiros, soldadores, pequenas empreitadas e impermeabilização.",
    icon: "🧱",
    items: [
      {
        id: "obra1",
        name: "Pedreiro / construtor civil",
        n: "Pedreiro / construtor civil",
        d: "Alvenaria, levantamento de paredes, reboco fino, fundações, pilares e betonilhas com nível rigoroso.",
        category: "obra",
        price: 1800,
        priceMzn: 1800,
        unit: "dia / diária",
        active: true,
        hasProviders: true,
        providerCount: 26,
        emg: false
      },
      {
        id: "obra2",
        name: "Pintor de interiores e exteriores",
        n: "Pintor de interiores e exteriores",
        d: "Preparação de paredes, aplicação de primário, tintas acrílicas laváveis, texturados e grafiato em fachadas.",
        category: "obra",
        price: 450,
        priceMzn: 450,
        unit: "m² / diária",
        active: true,
        hasProviders: true,
        providerCount: 22,
        emg: false
      },
      {
        id: "obra3",
        name: "Ladrilhador (colocação de azulejos e cerâmica)",
        n: "Ladrilhador (colocação de azulejos e cerâmica)",
        d: "Assentamento milimétrico de pisos porcelânicos, azulejos em cozinhas e casas de banho com niveladores.",
        category: "obra",
        price: 650,
        priceMzn: 650,
        unit: "m²",
        active: true,
        hasProviders: true,
        providerCount: 18,
        emg: false
      },
      {
        id: "obra4",
        name: "Gesseiro / estucador",
        n: "Gesseiro / estucador",
        d: "Aplicação de gesso liso nas paredes, sancas decorativas, tetos falsos em gesso e reparação de fissuras.",
        category: "obra",
        price: 700,
        priceMzn: 700,
        unit: "m²",
        active: true,
        hasProviders: true,
        providerCount: 11,
        emg: false
      },
      {
        id: "obra5",
        name: "Soldador e estruturas metálicas",
        n: "Soldador e estruturas metálicas",
        d: "Soldadura com elétrodo e MIG/TIG de perfis de aço, corrimões, vigas metálicas e reforços estruturais.",
        category: "obra",
        price: 3000,
        priceMzn: 3000,
        unit: "intervenção",
        active: true,
        hasProviders: true,
        providerCount: 14,
        emg: true
      },
      {
        id: "obra6",
        name: "Empreiteiro (pequenas e médias obras)",
        n: "Empreiteiro (pequenas e médias obras)",
        d: "Coordenação e execução chave-na-mão de remodelações, ampliações, anexos residenciais e reformas comerciais.",
        category: "obra",
        price: 15000,
        priceMzn: 15000,
        unit: "gestão de obra",
        active: true,
        hasProviders: true,
        providerCount: 8,
        emg: false
      },
      {
        id: "obra7",
        name: "Técnico de impermeabilização de telhados e lajes",
        n: "Técnico de impermeabilização de telhados e lajes",
        d: "Aplicação de telas asfálticas, membranas líquidas de poliuretano e eliminação definitiva de infiltrações e goteiras.",
        category: "obra",
        price: 650,
        priceMzn: 650,
        unit: "m²",
        active: true,
        hasProviders: true,
        providerCount: 13,
        emg: true
      }
    ]
  },
  {
    id: "jardinagem",
    cat: "Jardinagem & Exteriores",
    g: "jard",
    name: "Jardinagem & Exteriores",
    description: "Jardineiros, poda de árvores, rega automática, limpeza de quintais e terrenos, muros e piscinas.",
    icon: "🌿",
    items: [
      {
        id: "jard1",
        name: "Jardineiro / paisagismo",
        n: "Jardineiro / paisagismo",
        d: "Corte de relva, adubação, plantação de flores ornamentais e desenho paisagístico de jardins residenciais.",
        category: "jard",
        price: 1600,
        priceMzn: 1600,
        unit: "dia / intervenção",
        active: true,
        hasProviders: true,
        providerCount: 18,
        emg: false
      },
      {
        id: "jard2",
        name: "Poda e corte de árvores",
        n: "Poda e corte de árvores",
        d: "Poda de segurança para desobstrução de fios e telhados, abate controlado de árvores de grande porte.",
        category: "jard",
        price: 2500,
        priceMzn: 2500,
        unit: "árvore / intervenção",
        active: true,
        hasProviders: true,
        providerCount: 12,
        emg: true
      },
      {
        id: "jard3",
        name: "Instalação de rega automática",
        n: "Instalação de rega automática",
        d: "Montagem de tubagens subterrâneas, aspersores pop-up, programadores digitais e sensores de chuva.",
        category: "jard",
        price: 6500,
        priceMzn: 6500,
        unit: "sistema",
        active: true,
        hasProviders: true,
        providerCount: 8,
        emg: false
      },
      {
        id: "jard4",
        name: "Limpeza de quintais e terrenos",
        n: "Limpeza de quintais e terrenos",
        d: "Remoção de entulho verde, desmatação de capim alto, varredura profunda e nivelamento de solos.",
        category: "jard",
        price: 3500,
        priceMzn: 3500,
        unit: "terreno / serviço",
        active: true,
        hasProviders: true,
        providerCount: 15,
        emg: false
      },
      {
        id: "jard5",
        name: "Construção de muros e vedações",
        n: "Construção de muros e vedações",
        d: "Erguimento de muros em blocos de cimento, vedações em rede metálica e reforço perimetral de propriedades.",
        category: "jard",
        price: 1200,
        priceMzn: 1200,
        unit: "metro linear",
        active: true,
        hasProviders: true,
        providerCount: 10,
        emg: false
      },
      {
        id: "jard6",
        name: "Manutenção de piscinas (piscineiro)",
        n: "Manutenção de piscinas (piscineiro)",
        d: "Aspiração de fundo, controlo químico de pH/cloro, limpeza de filtros e prevenção de algas.",
        category: "jard",
        price: 2800,
        priceMzn: 2800,
        unit: "visita / mês",
        active: true,
        hasProviders: true,
        providerCount: 9,
        emg: false
      }
    ]
  },
  {
    id: "tech",
    cat: "Elite Tech",
    g: "tech",
    name: "Elite Tech",
    description: "Instalação técnica de câmaras CCTV, antenas parabólicas DSTV/GOtv e redes Wi-Fi/dados.",
    icon: "⚡",
    items: [
      {
        id: "tech1",
        name: "Montador de Câmaras de Segurança (CCTV)",
        n: "Montador de Câmaras de Segurança (CCTV)",
        d: "Instalação e configuração de câmaras IP/analógicas, DVR/NVR, visão noturna e acesso remoto no telemóvel.",
        category: "tech",
        price: 4500,
        priceMzn: 4500,
        unit: "instalação / kit",
        active: true,
        hasProviders: true,
        providerCount: 15,
        emg: true
      },
      {
        id: "tech2",
        name: "Instalador de Antenas Parabólicas (DSTV, GOtv)",
        n: "Instalador de Antenas Parabólicas (DSTV, GOtv)",
        d: "Fixação e alinhamento de precisão de antenas parabólicas, cablagem coaxial e sintonia de sinal de canais.",
        category: "tech",
        price: 2000,
        priceMzn: 2000,
        unit: "ponto / alinhamento",
        active: true,
        hasProviders: true,
        providerCount: 16,
        emg: true
      },
      {
        id: "tech3",
        name: "Instalador de Internet (Wi-Fi / Dados)",
        n: "Instalador de Internet (Wi-Fi / Dados)",
        d: "Passagem de cabos de rede UTP/Fibra, instalação de routers, repetidores Mesh e otimização de sinal Wi-Fi.",
        category: "tech",
        price: 2500,
        priceMzn: 2500,
        unit: "configuração / ponto",
        active: true,
        hasProviders: true,
        providerCount: 14,
        emg: true
      }
    ]
  }
];
